### ISSUE TITLE
I should be able to modify the field's position

### ISSUE THREAD

**Issue by talbotseb** [FriendsOfVictoire/WidgetTabBundle#6]
When I want to edit and reorder the fields, I can't drag & drop.
In the database, the field position of the widget_listing_item table is not taken into account.

**Comment by lenybernard** [comment]
I guess https://github.com/FriendsOfVictoire/WidgetTabBundle/pull/8 closes this issue. Right @BFoucher ?

**Comment by BFoucher** [comment]
Yes
